name: frontend
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - name: Lint
        run: yarn run lint
        working-directory: frontend
      - name: Build
        run: yarn build
        working-directory: frontend
